name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - run: flutter pub get
        working-directory: hotel-staff-flutter

      - run: pod repo update
        working-directory: hotel-staff-flutter/ios

      - run: flutter build ios --release --no-codesign
        working-directory: hotel-staff-flutter

      - run: mkdir Payload
        working-directory: hotel-staff-flutter/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: hotel-staff-flutter/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: hotel-staff-flutter/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hotel-staff-flutter/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
